/*
 * This source file was generated by the Gradle 'init' task
 */
package fr.parisnanterre.ProjetDEVOPSGMT.backend;

import org.junit.Test;
import org.springframework.boot.test.context.SpringBootTest;


import static org.junit.Assert.*;
import static org.junit.jupiter.api.Assertions.assertDoesNotThrow;

@SpringBootTest
public class AppTest {
   
    @Test public void checkApiRun() {
        
      assertDoesNotThrow(() ->App.main(new String[] {}));
    }
}
