spring:
  datasource:
    url: jdbc:mysql://localhost:3306/eco_nomade
    username: root
    password: 
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update # Options possibles : validate | update | create | create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQL8Dialect # Remplace par MySQL5Dialect si tu utilises MySQL 5.x

server:
  port: 8080 